version: "2"

services:
db:
  image: percona:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=p4ssw0rd
    - MYSQL_USER=typo3
    - MYSQL_PASSWORD=p4ssw0rd
    - MYSQL_DATABASE=TYPO3

typo3cms:
  image: hbokh/docker-typo3-cms:latest
  links:
    - db:db
  ports:
    - "80:80"
